default_job = "lint"
summary = false

[jobs.lint]
command = ["./scripts/lint.sh"]
need_stdout = true
watch = [
    "pyproject.toml",
    "uv.lock",
    ".python-version",
    ".gitignore",
    "./finalyze",
    "./scripts",
]

[jobs.format]
command = ["./scripts/format.sh"]
need_stdout = true
on_success = "back"
